<a href="https://colab.research.google.com/github/edgaryoungpilo-web/colab-files/blob/main/Datos_academicos_estudiantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio datos academicos estudiantes

In [10]:
#  Carga Librerias
import numpy as np
import pandas as pd


In [11]:
# Vectores de pesos
pesos = np.array([0.12, 0.08, 0.17, 0.17, 0.10,
                  0.03, 0.04, 0.04, 0.05, 0.20])


In [12]:
# Cargar archivo Excel
df = pd.read_excel('/content/drive/MyDrive/ClassFiles/Tablas de Datos Académicos.xls')

# Extraer solo las calificaciones
Z = df.iloc[:, 2:].to_numpy()

Z


array([[7.3  , 3.8  , 4.   , 8.4  , 3.2  , 6.5  , 5.8  , 5.9  , 9.9  ,
        3.8  ],
       [3.   , 7.4  , 7.   , 7.1  , 8.6  , 6.9  , 8.4  , 9.5  , 6.   ,
        5.9  ],
       [4.4  , 5.5  , 5.4  , 7.7  , 8.8  , 9.8  , 6.   , 4.2  , 9.9  ,
        3.5  ],
       [7.3  , 5.8  , 7.6  , 5.2  , 9.7  , 9.7  , 7.7  , 4.   , 7.8  ,
        7.   ],
       [4.9  , 3.2  , 6.5  , 5.   , 4.4  , 6.9  , 9.2  , 9.1  , 5.5  ,
        7.5  ],
       [5.15 , 5.6  , 5.5  , 7.75 , 5.9  , 6.7  , 7.1  , 7.7  , 7.95 ,
        4.85 ],
       [6.87 , 4.16 , 4.3  , 8.27 , 3.74 , 6.54 , 6.06 , 6.26 , 9.51 ,
        4.01 ],
       [4.98 , 4.35 , 5.85 , 5.37 , 6.87 , 7.92 , 6.87 , 5.19 , 6.96 ,
        5.4  ],
       [4.4  , 4.5  , 4.8  , 5.68 , 6.06 , 6.58 , 5.58 , 4.72 , 6.72 ,
        4.04 ],
       [7.51 , 7.825, 7.075, 7.315, 6.565, 6.04 , 6.565, 7.405, 6.52 ,
        7.3  ]])

In [13]:
# Pregunta 1
promedios_ponderados = pesos @ Z


In [14]:
# Pregunta 2
promedios_sin_pesos = Z.mean(axis=0)


In [15]:
# Pregunta 3
resultados = pd.DataFrame({
    "Promedio ponderado": promedios_ponderados,
    "Promedio sin pesos": promedios_sin_pesos
})

resultados

# Diferencia de promedios
resultados["Diferencia"] = (
    resultados["Promedio ponderado"] -
    resultados["Promedio sin pesos"]
)

resultados


Promedio ponderado  Promedio sin pesos  Diferencia
0              5.9455              5.5810      0.3645
1              5.5874              5.2135      0.3739
2              6.1260              5.8025      0.3235
3              6.7941              6.7785      0.0156
4              6.8744              6.3835      0.4909
5              7.6534              7.3580      0.2954
6              6.9392              6.9275      0.0117
7              6.1780              6.3975     -0.2195
8              7.7643              7.6760      0.0883
9              5.6469              5.3300      0.3169

In [16]:
# Pregunta 4
correlacion = np.corrcoef(Z)
correlacion


array([[ 1.        , -0.34531416,  0.42314502, -0.14294545,  0.00927663,
         0.68693407,  0.99620844,  0.20342103,  0.49365809, -0.20342103],
       [-0.34531416,  1.        ,  0.12853302, -0.17364657,  0.36205685,
         0.44480908, -0.26235784,  0.18968541,  0.21603851, -0.18968541],
       [ 0.42314502,  0.12853302,  1.        ,  0.57345952, -0.2913923 ,
         0.50334938,  0.44700103,  0.75571049,  0.96543699, -0.75571049],
       [-0.14294545, -0.17364657,  0.57345952,  1.        , -0.14252885,
        -0.27088061, -0.16307647,  0.77163299,  0.53566565, -0.77163299],
       [ 0.00927663,  0.36205685, -0.2913923 , -0.14252885,  1.        ,
         0.28921253,  0.04310139,  0.27822105, -0.05805201, -0.27822105],
       [ 0.68693407,  0.44480908,  0.50334938, -0.27088061,  0.28921253,
         1.        ,  0.7475531 ,  0.34101392,  0.63840213, -0.34101392],
       [ 0.99620844, -0.26235784,  0.44700103, -0.16307647,  0.04310139,
         0.7475531 ,  1.        ,  0.22674545

In [17]:
# Pregunta 5
from sklearn.decomposition import PCA

pca = PCA()
pca.fit(Z.T)

# Varianza
pca.explained_variance_ratio_

# Numero de componentes
np.cumsum(pca.explained_variance_ratio_)


array([0.43810037, 0.69533996, 0.89080392, 0.99768651, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [18]:
# Pregunta 6
#Estimar datos no almacenados
from sklearn.linear_model import LinearRegression

X = Z[:-1, :].T   # Todas menos una asignatura
y = Z[-1, :]      # Asignatura a estimar

modelo = LinearRegression()
modelo.fit(X, y)

y_estimado = modelo.predict(X)
