<a href="https://colab.research.google.com/github/edgaryoungpilo-web/colab-files/blob/main/Practica_4_266659.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practica 4 - Manipulacion de matrices

In [1]:
import numpy as np

# 1. Crear dos matrices 3x3 con valores aleatorios entre 1 y 10
matriz1 = np.random.randint(1, 11, size=(3, 3))
matriz2 = np.random.randint(1, 11, size=(3, 3))

print("Matriz 1:")
print(matriz1)

print("\nMatriz 2:")
print(matriz2)

# 2. Suma de matrices
suma = matriz1 + matriz2
print("\nSuma de las matrices:")
print(suma)

# 3. Resta de matrices (matriz1 - matriz2)
resta = matriz1 - matriz2
print("\nResta de las matrices (Matriz1 - Matriz2):")
print(resta)

# 4. Multiplicar la primera matriz por 2
multiplicacion_escalar = matriz1 * 2
print("\nMatriz 1 multiplicada por 2:")
print(multiplicacion_escalar)

# 5. Multiplicación matricial
multiplicacion_matricial = np.dot(matriz1, matriz2)
print("\nMultiplicación matricial (Matriz1 x Matriz2):")
print(multiplicacion_matricial)


Matriz 1:
[[ 9  5  2]
 [ 5 10  9]
 [ 8  7  7]]

Matriz 2:
[[ 4  5  5]
 [ 8  4 10]
 [ 1  8  1]]

Suma de las matrices:
[[13 10  7]
 [13 14 19]
 [ 9 15  8]]

Resta de las matrices (Matriz1 - Matriz2):
[[ 5  0 -3]
 [-3  6 -1]
 [ 7 -1  6]]

Matriz 1 multiplicada por 2:
[[18 10  4]
 [10 20 18]
 [16 14 14]]

Multiplicación matricial (Matriz1 x Matriz2):
[[ 78  81  97]
 [109 137 134]
 [ 95 124 117]]
