<a href="https://colab.research.google.com/github/edgaryoungpilo-web/colab-files/blob/main/Recomendacion_de_cursos_en_plataforma_e_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recomendación de cursos en plataforma e-learning

In [1]:
import numpy as np
import pandas as pd

# =========================
# MATRIZ DE EJEMPLO
# =========================
# (Puedes cambiarla si te dieron una específica)

A = np.array([
    [5, 4, 4, 1, 0, 0, 0, 0, 2, 1, 0, 0, 3, 2, 4],
    [4, 5, 5, 2, 0, 0, 0, 1, 2, 2, 0, 0, 3, 3, 4],
    [0, 0, 1, 4, 5, 5, 4, 4, 5, 4, 3, 2, 0, 0, 2],
    [0, 0, 0, 5, 4, 4, 5, 5, 4, 5, 3, 3, 0, 0, 2],
    [3, 2, 3, 0, 0, 1, 1, 0, 0, 1, 4, 5, 5, 4, 3],
    [2, 3, 2, 0, 1, 0, 0, 1, 0, 0, 5, 4, 4, 5, 3]
])

print("Matriz original:")
print(A)

# =========================
# PARTE 2: SVD
# =========================
U, S, VT = np.linalg.svd(A)

print("\nDimensiones:")
print("U:", U.shape)
print("S:", S.shape)
print("VT:", VT.shape)

print("\nValores singulares:")
print(S)

# =========================
# PARTE 3: APROXIMACIÓN
# =========================
k = 2  # puedes cambiar a 3

S_k = np.zeros((k, k))
np.fill_diagonal(S_k, S[:k])

U_k = U[:, :k]
VT_k = VT[:k, :]

A_k = U_k @ S_k @ VT_k

print("\nMatriz aproximada:")
print(np.round(A_k, 2))

# =========================
# PARTE 4: ERROR
# =========================
def error_relativo(A, A_k):
    return np.linalg.norm(A - A_k) / np.linalg.norm(A)

print("\nErrores para diferentes k:")

for k in range(1, 6):
    S_k = np.zeros((k, k))
    np.fill_diagonal(S_k, S[:k])
    A_k = U[:, :k] @ S_k @ VT[:k, :]
    error = error_relativo(A, A_k)
    print(f"k={k} -> error={error:.4f}")

# =========================
# PARTE 5: VALOR FALTANTE
# =========================
A_missing = A.copy()
A_missing[0, 4] = 0  # ocultamos un valor

U, S, VT = np.linalg.svd(A_missing)

k = 2
S_k = np.zeros((k, k))
np.fill_diagonal(S_k, S[:k])

A_reconstruida = U[:, :k] @ S_k @ VT[:k, :]

print("\nValor estimado:")
print(A_reconstruida[0, 4])

# =========================
# PARTE 6: FACTORES LATENTES
# =========================
print("\nPrimer factor (U):")
print(U[:, 0])

print("\nPrimer factor (VT):")
print(VT[0])

Matriz original:
[[5 4 4 1 0 0 0 0 2 1 0 0 3 2 4]
 [4 5 5 2 0 0 0 1 2 2 0 0 3 3 4]
 [0 0 1 4 5 5 4 4 5 4 3 2 0 0 2]
 [0 0 0 5 4 4 5 5 4 5 3 3 0 0 2]
 [3 2 3 0 0 1 1 0 0 1 4 5 5 4 3]
 [2 3 2 0 1 0 0 1 0 0 5 4 4 5 3]]

Dimensiones:
U: (6, 6)
S: (6,)
VT: (15, 15)

Valores singulares:
[21.24661211 15.05171379  8.21802793  2.51684176  2.13465926  1.26496643]

Matriz aproximada:
[[ 3.29  3.3   3.28  0.42 -0.04 -0.03 -0.04  0.19  0.66  0.67  1.96  2.
   3.56  3.32  3.18]
 [ 3.54  3.55  3.57  0.79  0.28  0.3   0.29  0.54  1.03  1.05  2.35  2.35
   3.84  3.59  3.57]
 [-0.03 -0.01  0.48  4.37  4.38  4.39  4.41  4.41  4.32  4.39  3.06  2.59
   0.08  0.1   1.95]
 [-0.12 -0.09  0.42  4.57  4.59  4.59  4.62  4.61  4.51  4.58  3.15  2.66
  -0.01  0.02  1.96]
 [ 3.61  3.62  3.65  0.93  0.42  0.43  0.42  0.67  1.17  1.2   2.48  2.47
   3.91  3.65  3.69]
 [ 3.46  3.47  3.49  0.82  0.33  0.34  0.33  0.58  1.06  1.08  2.32  2.32
   3.75  3.5   3.5 ]]

Errores para diferentes k:
k=1 -> error=0.6360
k=2 -> 